package it.polito.ai.lab4.business.services.accounting;

public enum ResultInfo {
	REGISTRATION_OK,
	REGISTRATION_ERR_USERNAME_ALREADY_EXISTS,
	REGISTRATION_ERROR,
	
	LOGIN_SUCCESSFUL,
	LOGIN_FAILED,
	
	PASSWORD_CHANGE_OK,
	PASSWORD_CHANGE_FAILED,
	
	USER_PROFILE_UPDATE_OK,
	USER_PROFILE_UPDATE_FAILED,
	
}
