INSERT INTO education_levels (id, value) values (1, 'LICENZA ELEMENTARE');
INSERT INTO education_levels (id, value) values (2, 'LICENZA MEDIA');
INSERT INTO education_levels (id, value) values (3, 'DIPLOMA DI ISTRUZIONE SECONDARIA SUPERIORE');
INSERT INTO education_levels (id, value) values (4, 'LAUREA DI PRIMO LIVELLO');
INSERT INTO education_levels (id, value) values (5, 'LAUREA SPECIALISTICA');
INSERT INTO education_levels (id, value) values (6, 'MASTER UNIVERSITARIO DI PRIMO LIVELLO');
INSERT INTO employments (id, value) values (1, 'STUDENTE');
INSERT INTO employments (id, value) values (2, 'DISOCCUPATO');
INSERT INTO employments (id, value) values (3, 'OCCUPATO AUTONOMO');
INSERT INTO employments (id, value) values (4, 'OCCUPATO PERMANENTE');
INSERT INTO employments (id, value) values (5, 'OCCUPATO TEMPORANEO');
INSERT INTO employments (id, value) values (6, 'PENSIONATO');
INSERT INTO fuels (id, value) values (1, 'BENZINA');
INSERT INTO fuels (id, value) values (2, 'DIESEL');
INSERT INTO fuels (id, value) values (3, 'GPL');
INSERT INTO fuels (id, value) values (4, 'IBRIDA');
INSERT INTO fuels (id, value) values (5, 'METANO');
INSERT INTO fuels (id, value) values (6, 'AUTO ELETTRICA');
INSERT INTO car_sharing_services (id, name) values (1, 'ENJOY');
INSERT INTO car_sharing_services (id, name) values (2, 'CAR2GO');
INSERT INTO car_sharing_services (id, name) values (3, 'BLUETORINO');
INSERT INTO travel_documents (id, name, cost) values (1, 'GIORNALIERO', 5.00);
INSERT INTO travel_documents (id, name, cost) values (2, 'CORSA SINGOLA', 1.50);
INSERT INTO travel_documents (id, name, cost) values (3, 'CARNET 5', 6.50);
INSERT INTO travel_documents (id, name, cost) values (4, 'CARNET 15', 17.50);
INSERT INTO status (id, value) values (1, 'INCOMPLETE');
INSERT INTO status (id, value) values (2, 'ENABLED');
INSERT INTO status (id, value) values (3, 'BANNED');
